### ISSUE TITLE
x3x description has a mistake

### ISSUE THREAD

**Issue by AlexNessy** [Zukoix/Saber-Monkey-Mod#1]
In the description for the x3x upgrade there is a spelling mistake which mistakes to for yo (I presume). Image below

![image](https://user-images.githubusercontent.com/93941936/140797305-393f0093-f14d-4745-b6fa-5bfbe4a248f2.png)

**Comment by Zukoix** [comment]
fuck

**Comment by DaisyD2** [comment]
050 does too
